version: '3'

services:
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./django_project:/django_project
    ports:
      - 8000:8000
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
